### ISSUE TITLE
Enhance to permit specification of address search area

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/configurable-place-finder#31]
Currently, the app uses the extents of the basemap for its search area, so one gets results such as
![image](https://cloud.githubusercontent.com/assets/2125181/4563293/d0cb32d6-4f0c-11e4-96ed-9581bbdb89c0.png)

**Comment by LindsayThomas** [comment]
We are no longer adding any enhancements to this version of the application. I am closing this issue.
